version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: prepare tools
          command: |
            sudo -E bash ./scripts/circleci-linux.sh
      - run:
          name: prepare go mod
          command: |
            make bootstrap
      - run:
          name: lint
          command: |
            make check
      - run:
          name: test
          command: |
            sudo -E "PATH=$PATH" make test
      - store_test_results:
          path: build/test/
      - run:
          name: compile driver
          command: |
            make release
      - store_artifacts:
          path: pkg/linux_amd64.zip
          destination: linux_amd64.zip